//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hw1WindowsFormPt1.StringModify {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringModify.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vowelCount", ReplyAction="http://tempuri.org/IService1/vowelCountResponse")]
        int vowelCount(string vowel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vowelCount", ReplyAction="http://tempuri.org/IService1/vowelCountResponse")]
        System.Threading.Tasks.Task<int> vowelCountAsync(string vowel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/capitalCount", ReplyAction="http://tempuri.org/IService1/capitalCountResponse")]
        int capitalCount(string capital);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/capitalCount", ReplyAction="http://tempuri.org/IService1/capitalCountResponse")]
        System.Threading.Tasks.Task<int> capitalCountAsync(string capital);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reverseString", ReplyAction="http://tempuri.org/IService1/reverseStringResponse")]
        string reverseString(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reverseString", ReplyAction="http://tempuri.org/IService1/reverseStringResponse")]
        System.Threading.Tasks.Task<string> reverseStringAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Hw1WindowsFormPt1.StringModify.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Hw1WindowsFormPt1.StringModify.IService1>, Hw1WindowsFormPt1.StringModify.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int vowelCount(string vowel) {
            return base.Channel.vowelCount(vowel);
        }
        
        public System.Threading.Tasks.Task<int> vowelCountAsync(string vowel) {
            return base.Channel.vowelCountAsync(vowel);
        }
        
        public int capitalCount(string capital) {
            return base.Channel.capitalCount(capital);
        }
        
        public System.Threading.Tasks.Task<int> capitalCountAsync(string capital) {
            return base.Channel.capitalCountAsync(capital);
        }
        
        public string reverseString(string input) {
            return base.Channel.reverseString(input);
        }
        
        public System.Threading.Tasks.Task<string> reverseStringAsync(string input) {
            return base.Channel.reverseStringAsync(input);
        }
    }
}
