'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace StringModify2
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="StringModify2.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/vowelCount", ReplyAction:="http://tempuri.org/IService1/vowelCountResponse")>  _
        Function vowelCount(ByVal vowel As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/vowelCount", ReplyAction:="http://tempuri.org/IService1/vowelCountResponse")>  _
        Function vowelCountAsync(ByVal vowel As String) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/capitalCount", ReplyAction:="http://tempuri.org/IService1/capitalCountResponse")>  _
        Function capitalCount(ByVal capital As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/capitalCount", ReplyAction:="http://tempuri.org/IService1/capitalCountResponse")>  _
        Function capitalCountAsync(ByVal capital As String) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/reverseString", ReplyAction:="http://tempuri.org/IService1/reverseStringResponse")>  _
        Function reverseString(ByVal input As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/reverseString", ReplyAction:="http://tempuri.org/IService1/reverseStringResponse")>  _
        Function reverseStringAsync(ByVal input As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits StringModify2.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of StringModify2.IService1)
        Implements StringModify2.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function vowelCount(ByVal vowel As String) As Integer Implements StringModify2.IService1.vowelCount
            Return MyBase.Channel.vowelCount(vowel)
        End Function
        
        Public Function vowelCountAsync(ByVal vowel As String) As System.Threading.Tasks.Task(Of Integer) Implements StringModify2.IService1.vowelCountAsync
            Return MyBase.Channel.vowelCountAsync(vowel)
        End Function
        
        Public Function capitalCount(ByVal capital As String) As Integer Implements StringModify2.IService1.capitalCount
            Return MyBase.Channel.capitalCount(capital)
        End Function
        
        Public Function capitalCountAsync(ByVal capital As String) As System.Threading.Tasks.Task(Of Integer) Implements StringModify2.IService1.capitalCountAsync
            Return MyBase.Channel.capitalCountAsync(capital)
        End Function
        
        Public Function reverseString(ByVal input As String) As String Implements StringModify2.IService1.reverseString
            Return MyBase.Channel.reverseString(input)
        End Function
        
        Public Function reverseStringAsync(ByVal input As String) As System.Threading.Tasks.Task(Of String) Implements StringModify2.IService1.reverseStringAsync
            Return MyBase.Channel.reverseStringAsync(input)
        End Function
    End Class
End Namespace
